language: node_js
node_js:
- '4.1'
before_install:
- openssl aes-256-cbc -K $encrypted_d5913473cb86_key -iv $encrypted_d5913473cb86_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- cp deploy_key ~/.ssh/id_rsa
before_script:
- npm install -g gulp
script:
- gulp
- bash deploy
